### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by zvaehn** [51seven/Customer-Key-Chain#1]
It seems that files in app/tmp/\* are not excluded from git tracking, but it's already written in .gitignore.

**Comment by timomeh** [comment]
In deinem ersten und zweiten Commit hast du noch keine .gitignore gehabt, weswegen app/tmp/\* auch mitgepushed wurde. Du siehst ja auch, dass app/tmp/ nach deinem ersten Commit nicht mehr verändert wurde. Ab dem 3. Commit wird jetzt also app/tmp/\* ignoriert, also komplett in Ruhe gelassen, weder gelöscht, noch geupdated.
Um app/tmp/\* zu löschen einfach `git rm -r app/tmp/`[...]. Je nachdem, ob Cake die tmp-Ordner selbst erstellen kann entweder einfach alles löschen oder nur den Inhalt.

Beim nächsten Mal die .gitignore ganz zu Anfang hinzufügen ;)

**Comment by zvaehn** [comment]
ahh. thx!

**Comment by timomeh** [comment]
Wenn du leere Ordner pushen möchtest (git pushed normalerweise leere Ordner nicht mit, selbst wenn du sie angelegt hast), leg einfach in dem Ordner eine leere Datei namens .gitkeep an.
Ist nichts offizielles, kannst sie auch cmd-shift-n nennen, hat sich nur irgendwie so eingebürgert, dann weiß man einfach dass sie als Platzhalter da ist.

**Comment by zvaehn** [comment]
deshalb wahrscheinlich auch diese “empty” Dateien oder?

**Comment by timomeh** [comment]
Jep!
